const coupons = [
  {
    code: 'WELCOME10',
    description: '10% off for new customers',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 500,
    maxDiscount: 200,
    usageLimit: 100,
    usageCount: 0,
    isActive: true,
    validUntil: new Date('2024-12-31'),
    applicableCategories: [],
    applicableProducts: [],
  },
  {
    code: 'SAVE20',
    description: '20% off on orders above ₹1000',
    discountType: 'percentage',
    discountValue: 20,
    minOrderAmount: 1000,
    maxDiscount: 500,
    usageLimit: 50,
    usageCount: 0,
    isActive: true,
    validUntil: new Date('2024-12-31'),
    applicableCategories: [],
    applicableProducts: [],
  },
  {
    code: 'FLAT100',
    description: 'Flat ₹100 off on all orders',
    discountType: 'fixed',
    discountValue: 100,
    minOrderAmount: 300,
    maxDiscount: 100,
    usageLimit: 200,
    usageCount: 0,
    isActive: true,
    validUntil: new Date('2024-12-31'),
    applicableCategories: [],
    applicableProducts: [],
  },
  {
    code: 'TEES30',
    description: '30% off on T-Shirts',
    discountType: 'percentage',
    discountValue: 30,
    minOrderAmount: 0,
    maxDiscount: 300,
    usageLimit: 75,
    usageCount: 0,
    isActive: true,
    validUntil: new Date('2024-11-30'),
    applicableCategories: [], // Will be set after categories are created
    applicableProducts: [],
  },
  {
    code: 'MUGS50',
    description: 'Buy 2 mugs, get 50% off on second',
    discountType: 'percentage',
    discountValue: 50,
    minOrderAmount: 0,
    maxDiscount: 200,
    usageLimit: 30,
    usageCount: 0,
    isActive: true,
    validUntil: new Date('2024-10-31'),
    applicableCategories: [], // Will be set after categories are created
    applicableProducts: [],
  },
];

export default coupons;
